language: node_js
node_js:
- '13'
- '12'
- '11'
- '10'
- '9'
- '8'
- '7'
- '6'
env:
  global:
  - secure: k4qXCoK4MLj0kaOBG13+pzEMYoXsFE6z5YfRDRBzFVLyzIMq2+/AELBYldY5xUizxe5WaYu+P23hG3WAEmIAVUvXhMnYweeG0QsEqwGIzAC5bRrPjE2EmwKvaW3FLT1AqQPJkiTIHYqLSh/eeGq5h2eQcl3fjgIV9ToSgzMHjFlMlKQTnSlClwW+aBnZoFiZvexJDyulPI3RKhVYIJc6xu9QbVVIf5Ny4elUL0aPXEj+bnb1a382bAUkDuN0c2vcN9R3W89dotrvwxXWa+M+gVsduFp9JZ2Hgx24CQXa4TjJZJjS57wjuJ4jUQ4kOh57xtbdED5uzDrD/eAnytUN5uEB8+SuIhn/4Dw83p8op8yq3EJx2Xpolp+qWLb/8H/RypuVJv72ZOmihrlKzHyGasfd4Wb3FSYYpiGbfPcl4bGv59JfayW142AfaZYuqYyCzIATIaEkXudJR54EyJmqxx/6R4qIuOs5GiTW6f2evcwdM/m3jT+zgN2hAqNe2FrhXSj3jb3a4IDCt6kV2ggBfXJz2s9xN0FCpIBgoweoyox84K5xwx0loo/xg2ZFf8YG7YoBvg20MPjAB434Lw7l/VIZGQh/ftmF3ezPjeG2K5A457NO2Jt62rs4IluH6ZR1CwL5lcL/dq1IVMVuyrxzxiuw6VqzqjDM5UQ+lAjl9GU=
  - secure: 17+/9+ByIOx29MlTusX0mnsu0b78RTX42j0yW2A0eSf2cHhxV56lKAYU3TRaCXOhpYPPVdlUdBzoXVrDD03nHL2gnDGQoY7Q7vP2Tb2q/y6AlgyVUuce7J6Py1s1iOU9ty1VMfv7iIDhFUI9Lvv+/EA/Ege9H09n8tO9t5UDDh1xhXJOsvE4gwezZUBRvhLMkarRJBGTfy8IKv2Jc2n55Qi+xyDu9NqcKtZQHiDn2Eyyc1Ll+0hfToAjWNep3PFrpDtFKP9MeQDS8R/0kVeDcw/eoQSeQhbkD61AQIBeqKVFXg553uXIWYZKNWXps9f8YYKABbbB6UPkgsXZvklrNKowdpZRMx2MARaF0Ex5YdAB+BsROYNKlUwmR17I3ZES3QDJLb8LFbDdrRyvfsvcODnu+1shn2YGUph2+BGKhjDaM/MsumRJebmvVDgCMvakNKjSAEWSJUP5rF4WUmUPL8AF09jgQFaUgKbznLh8RzaWv4DVWlfK8255OCy1mjeYXDWwIK+hWlQYXpHTlvxIlh4oAh+JWicpHYebHr3CyxrlYrgfVZWNpWuidRVClZotLU36gl2Np0XHYmdBYXEtY8rz3JqtTyhPJFeD1ePaEmjihHAfLAI9yyc4oJDgTAHJXGfbNr9ubN1jn6POUqV/ZGnWVL4Pr604cXfjdbEyqyg=
