language: node_js
node_js:
- '13'
- '12'
- '11'
- '10'
- '9'
- '8'
env:
  global:
  - secure: xGmGFNRL1ieiXZHUp+hczihj2Hfpml05W7MsjBYbtqKrjWgLGj3SISpLlM9nagunm/0mw5pJ/UjLL7j5j8YAYDzOgzBMqATxYVg+p7R3dAOlAQkrsCl4IYjgZxyaro8PwKJBUO0tqxcmdrWS4wYGU6Q+wdahnZB1dntOKxsxsqbLlCCZcQBAoX+rpXp9r8W3KrSU3qsKU2DUA0qKBE350GuP6wnhEXlrE7JunucKkNUJfurVluHUDDP4CNce70RpdeDkP3Z/zYmqgaw0fVb0qJcAMBKwivtmEckG7udIhytdrjwxH5TmKaujbOQmWDJnpDfxRD0Vm9HLD8ysQzH4EOK6ySXyY7CEzReGGhj0T5EBBwwcempZzelOE+df6BoxRG+hMnbHjqwWFfeNbEap4eTGUhxWHxFVLGR3ULl4/uR1a71ZQR+KDIkUK1wcFYGW3SHmAR8kpdtRPiZNxhET7+4hwe7DLWg80/e3TGybsmNGFlf7Dbub9xk5Q9RK3YZB4EBwSWyMF0KedajtF3pTSEALbUD3mIzO2bHZE9YqjzgZHJ8w8bN9UMdWx9A3SGcxc4hND501Eh7zCHVyAgJlY9cxvaKmwCKDEdhXma0TSsVobRg9/gJZZDsd0B1LSrDLhBbh2nasLyExTiHl/LegGFZ6nS2ERnYWwvfuf0g0DLY=
  - secure: o2y/G6DafnEow+TjIgrpeDWVnQuPrroIJPw9zHGuyz2zFe3NSQlN+ViXlji0/mFkUVThPSXIiJKnaIomHEmRKLAuNZz/NhKWVD6et2Kq2x9Wcky79yLu1CzpuUTnclXR+qEy1DHVrn9gKF2sZx0NTDOzgorFSnO6gXcmoFu++LiQD6OJIrPfwt5AXPM2i9t//hFCY1Y1XEzpTSbcMKGfGhfbHCa5y9V6Er+gGMvEbol7+eXj6RI6ZR7Efcl4E9Jnaud8Oq5HTpMEk7CIWu5Y4zmwjLo0fYRXvVRFlSq7JtQxhjuzRJbq3n6hAsIDAvtaYGhqGo2bnp+qz8duh+H6EHOaEPw9yuXRftt5PhR6JAgaq19qzGXQStllzC46RMbcXAiZMicTPPtiYfX2qFgqbnggRwk5hvO5VLc7/eINlKZEneElE4GVT//jGBKcHu6AAAIN46jyeerq+UvBTvUPZvfO/Y4MiwVpfovCTK9eUM0gQvz0ZjhHj2xz9cagSlFpzgJMGFdi/QMDFW3mvp9uOoEXSQgCZUnU4xM1qrOQBIEnWYY28AshbtQqT6hoTMEQJ1xzCWhLXxOZQW0UlFBc0XPtHW59BTPeaFA7E6yfzxFjbCoSM7EZWmp2Zb8qtENUsL9bSvu8oY5pnxXmiSmkIElIr6xY6PpopXa+Rk6DHrY=
