language: node_js
node_js:
- '13'
- '12'
- '11'
- '10'
- '9'
- '8'
- '7'
- '6'
env:
  global:
  - secure: m6AHszesCsOBd0qAzuR8ErWXI497ZmkRh92l9ZILsI1w5hh8nVEB3N/lFu3kGOOKPT7CSCS5PXI9XRRfqYoqNlAmtVNyUvr5L3zWyE2bg67E2dGvyrL92ZAbnQoscPGpKvmwFc+n7/hBjl7uXhemdUbGEal0fpLQzjKQcdlVxc+fo754Mf7WKFpM1MBaoHaiqXLiZOCRxJGnzifmmjoTU1wuzvXc2HcWMJiS7/WRkKKLV9FEpazXfM0aRjsIPkv9MsUdDo1SUt44MEyBAJlXZyF/jdHQXHTZmf5RxRAXCbCNRWOKm7A0hRUj6kvRMnxlGg6sSaiQNA1FCOuuOVvYqBBmkHO/mZLcmnUSf+pwXexVGW/Iegb5+VQgKCnd7YbFS4hToLdncEOUht37aplXmRGa6gbfNFTUBc3n8LlxXkWXNNGUIMETnODptpEujRvCSrgx5jN/gYBiATNgBepmOyrq/X6zLrNHZ9KVXCGf2N/n8XcAJMojrb5u2uh0yIxpVDuoMovYLJzQmHl6XySnNqnko/2wWUKzqMv7L53SZAuUelkTLoxhMLRFHqdtb1NBHwiuXL4FnptFsnYd/6/sF/hkhWmz6ZJwb50FFDwLyWdIjo8Aq8cCqR6ThEmywwDIKQoMCUcqmAbNuwiM8qMFrVXcgiEkSKolkwgC08AMESo=
  - secure: dwF8f11mk+x2A1z0zKc7aOAKLK04ioEBNuvYT7wzmbQdXD4TcUF1TB0nWclZv2YbkRjhlcj1Qzhtxx9WtiZoWz1J36rNQYx4DnUlKNhoMYTGM+SojVOeVGn6B+v1BM2Wa1n/lAfhf3Oflhx1gPdAdHBHkqQNqoh9cWihT9GOnU5G1vu7lfDyB+28V6oP+CtawYURd7AY8RUgyLM9Phb0HQ4IMt7kw4TsKByVQrQTaSwzGkYKtY3F6p1m9biT8Ox8BoqoTK3Rv7uqrpl3KB6aJNMyPj6hrbup/JHu40pCY99DCdY+oilmdx6im+V9I50vjSJ+I0B3Mixwu9Uueo0VC9ezy5OPUEMO9YB9XNrGGRhwd9dA6PF7EXNH+YzkDXVdrTCjXl+Y9l0gYfmZX5+Rm9jnXNr0y9MzqSJvvk4MI+LVG96XK6hNr6uTKxuamk6YEloRm2eUFhhQQZpqp1dnR/8YZhUZS3vtWqnZY3c+jB120Z+rQ0VucbTlGgXkhXMhRY+SBUiEXHexcK60OMso13/8SGBAfbOEjysiQahPp6flolSi9BW13N7xKHV9tQLRAxTYzfUOapy/ifU9FwV0w+A+++oRnL4OVe2DKM8kBacSv9bYhRdxMqSZGODaEAlzRUBZOZaAgRnB8e4Gdxg5TZL4M4FlPCzDfdn82Rs0gR4=
